### ISSUE TITLE
A() in cusparse.py

### ISSUE THREAD

**Issue by mjabri** [grlee77/python-cuda-cffi#1]
Hello
Is A() below returning transpose correct? Also, i looked at https://github.com/scipy/scipy/blob/master/scipy/sparse/compressed.py and could not find thse methods. Am I looking at wrong spot?
Thanks

```
"""
start of: subset of methods in scipy.sparse.compressed._cs_matrix
"""
@property
def A(self):
    "The transpose operator."
    return self.todense()
```

**Comment by grlee77** [comment]
This was a bug in the documentation string.  I have now fixed it in #2 which has been merged into master.

Use `.T` for transpose (or `.H` for complex transpose).

`.A` returns a dense representation of the matrix

**Comment by grlee77** [comment]
As to why you did not see the methods in the scipy file you linked:

scipy CSR matrices inherit some methods from the base `spmatrix` class which is defined in a separate file.  see here for `todense`, for example:
https://github.com/scipy/scipy/blob/fc552decdb4b55f9c494689110e9a326c9053884/scipy/sparse/base.py#L585

**Comment by mjabri** [comment]
Great. Thanks!!
