### ISSUE TITLE
Is there a way to update a CSR matrix on GPU after it has been created?

### ISSUE THREAD

**Issue by mjabri** [grlee77/python-cuda-cffi#3]
I created a CSR matrix using the constructor in cusparse.py and used it on a GeForce 980m and it works pretty well! I can read back after running my code on the GPU the CSR to the host and everything looks good (compared results to sparse computation on CPU only).

I wanted to know whether there is a way to update a CSR matrix after it has been created on the GPU. I looked at the cusparse methods and it does not seem to a direct method. I tried to del-ete the CSR object and re-creating it but I am not sure this is actually working as when I read back the CSR to the host it shows some corruption.

**Comment by grlee77** [comment]
I assume you mean to leave the data indices the same, but just update the values?  If so, I think the method `_with_data' should be able to change just the values:

``` python

# the following should work for new_data as ndarray or gpuarray.  If gpuarray, the overhead of transferring from host to gpu is avoided
mycsr = mycsr._with_data(new_data, copy=False)`

# can also do simple multiplication or division with a scalar via:
mycsr *= 2.0  # multiply all values by 2
mycsr /= 2.0  # divide all values by 2
```

I can't test this at the moment, so let me know if the above doesn't work.   

see:
https://github.com/grlee77/python-cuda-cffi/blob/30498536d3efabd65649c11979169fef82162295/cuda_cffi/cusparse.py#L1390

**Comment by mjabri** [comment]
Thanks!! I will give this a try and let you know.

**Comment by grlee77** [comment]
closing for now.  feel free to reopen if the suggestion above did not work
